apiVersion: v1
kind: Service
metadata:
  name: payment-service-service
  labels:
    app: payment-service-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30358
      protocol: TCP
  selector:
    app: payment-service-app
  type: LoadBalancer