apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  labels:
    app: payment-service-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SERVER_ADDRESS: "0.0.0.0"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/paymentservice"
  SPRING_PROFILES_ACTIVE: "default"