name: CI/CD - Java MicroServiÃ§o de Pagamento

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI - Build, Test & Sonar
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
  
      - name: Build & Test
        run: mvn clean verify
  
      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "EXECUTANDO SONARQUBE"
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml\
            -Dsonar.qualitygate.wait=true
      
      - name: Print Test Coverage
        run: |
          MISSED=$(xmllint --xpath "string(//counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
          COVERED=$(xmllint --xpath "string(//counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
      
          TOTAL=$((MISSED + COVERED))
          COVERAGE=$(awk "BEGIN {printf \"%.2f\", ($COVERED/$TOTAL)*100}")
          
          echo "--------------------------------------"
          echo "ðŸ§ª Test Coverage: $COVERAGE%"
          echo "--------------------------------------" 
  cd:
    name: CD - Build Docker & Deploy
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Build application
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ms-payment:latest .

      - name: Deploy
        run: echo "Deploy executado com sucesso"
